logging.level:
  root: INFO

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
        min-response-size: 1024
    servlet.session:
        timeout: 3600s #1个小时过期

spring:
  profiles.active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet.multipart:
    max-file-size: 50MB
    max-request-size: 50MB
    resolve-lazily: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weblog?characterEncoding=utf8&useSSL=false
    username: root
    password:
    hikari:
      pool-name: HikariCP
      connectionTimeout: 5000
      maximum-pool-size: 20
      minimum-idle: 3
      idle-timeout: 600000  # 空闲连接保留10分钟
      max-lifetime: 3600000 # 一个连接最长60分钟

mybatis.configuration.mapUnderscoreToCamelCase: true